### ISSUE TITLE
Cope with different formats of logcat Start proc messages

### ISSUE THREAD

**Issue by julianharty** [ISNIT0/logcat-filter#2]
There are at least 2 formats of the Start proc message.
Perhaps they vary by Android version?
1. `HTC 510 4.4.3 v2ActivityManagerStart proc org.kiwix.kiwixmobile for activity org.kiwix.kiwixmobile/.utils.SplashActivity: pid=9137 uid=10344 ...`
2. `Nexus 7 6.0.1 ActivityManagerStart proc 19482:org.kiwix.kiwixmobile/u0a183 for activity org.kiwix.kiwixmobile/.utils.SplashActivity`

I've saved a copy of what seems to be a valid regex: `Start proc \d*:*org.kiwix.kiwixmobile` which is also available with the examples above at https://regex101.com/r/HWBLxZ/1

What I'm trying to discover is how to use a/the regex in watchForPID in `index.js`

**Comment by ISNIT0** [comment]
Both of these log formats now work, opening a new ticket per device from now on.
